import sys, json
sys.path.insert(0, '.')
from pathlib import Path
from collections import defaultdict
from core_pipeline import load_pdf, query, _node_key

def cluster_analysis(survivors, graph_index):
    """
    For each surviving node, compute:
      - intra_degree: edges to OTHER survivors (intra-cluster density)
      - total_degree: total edges in full graph
      - isolation: node has zero edges to any other survivor
    Then find connected components within survivor subgraph.
    """
    survivor_keys = {_node_key(n): i for i, n in enumerate(survivors)}

    intra = defaultdict(int)   # key → edges to other survivors
    total = defaultdict(int)   # key → total graph degree

    for key in survivor_keys:
        fwd = graph_index._fwd.get(key, [])
        bwd = graph_index._bwd.get(key, [])
        total[key] = len(fwd) + len(bwd)
        for nk, _ in fwd + bwd:
            if nk in survivor_keys:
                intra[key] += 1

    # Connected components via union-find
    parent = {k: k for k in survivor_keys}
    def find(x):
        while parent[x] != x:
            parent[x] = parent[parent[x]]
            x = parent[x]
        return x
    def union(a, b):
        parent[find(a)] = find(b)

    for key in survivor_keys:
        for nk, _ in graph_index._fwd.get(key, []):
            if nk in survivor_keys:
                union(key, nk)

    comps = defaultdict(list)
    for k in survivor_keys:
        comps[find(k)].append(k)

    return intra, total, comps, survivor_keys

FAILING = {
    "openai-services-agreement.pdf": [
        "Who owns the Output generated by the Services?",
        "What law governs this agreement for US customers?",
        "How many days advance notice does OpenAI give for price changes on the Pricing Page?",
    ],
    "Exhibit 10.24.pdf": [
        "Who are the two parties to this agreement?",
        "What does CoreWeave warrant about the Services' performance?",
        "How many hours does Customer have to notify CoreWeave of a Security Incident?",
        "What retention policy must CoreWeave implement for Processed Customer Data?",
    ],
}

SEP = "=" * 70

for doc_name, questions in FAILING.items():
    print(f"\n{SEP}", flush=True)
    print(f"DOC: {doc_name}", flush=True)
    print(SEP, flush=True)
    pipeline = load_pdf(Path('sample_docs') / doc_name, reuse_existing=True)
    gi = pipeline.retriever._graph_index

    for q in questions:
        print(f"\n{'─'*60}", flush=True)
        print(f"Q: {q}", flush=True)
        result = query(pipeline, q)
        survivors = result.get('surviving_nodes') or []
        print(f"  answerable={result['answerable']}  vote_frac={result.get('vote_fraction')}  survivors={len(survivors)}", flush=True)

        intra, total, comps, skeys = cluster_analysis(survivors, gi)

        # Sort components by size
        sorted_comps = sorted(comps.values(), key=lambda c: -len(c))
        print(f"  graph components in survivors: {len(sorted_comps)}", flush=True)
        print(f"  largest cluster size: {len(sorted_comps[0]) if sorted_comps else 0}", flush=True)
        isolated = sum(1 for c in sorted_comps if len(c) == 1 and intra.get(c[0], 0) == 0)
        print(f"  isolated nodes (no survivor edges): {isolated}/{len(survivors)}", flush=True)

        # Show top 5 survivors with their intra-degree
        print(f"  top 10 survivors (rank | intra_deg | total_deg | type | source):", flush=True)
        for i, n in enumerate(survivors[:10]):
            key = _node_key(n)
            id_ = intra.get(key, 0)
            td_ = total.get(key, 0)
            src = (n.get('source_text') or '')[:70]
            print(f"    [{i:2d}] intra={id_:2d} total={td_:3d} {n['type']:12s} | {src}", flush=True)

        # Show the densest cluster's top nodes (likely the right answer zone)
        print(f"  densest cluster (top 5 nodes by intra-degree):", flush=True)
        biggest = sorted_comps[0] if sorted_comps else []
        cluster_nodes = [(k, intra.get(k,0), total.get(k,0), skeys[k]) for k in biggest]
        cluster_nodes.sort(key=lambda x: -x[1])
        for key, id_, td_, rank in cluster_nodes[:5]:
            node = gi._by_key.get(key) or {}
            src = (node.get('source_text') or '')[:80]
            print(f"    rank={rank:3d} intra={id_:2d} {node.get('type','?'):12s} | {src}", flush=True)
