import sys, json
sys.path.insert(0, '.')
from pathlib import Path
from core_pipeline import load_pdf, query

FAILING = {
    "openai-services-agreement.pdf": [
        "Who owns the Output generated by the Services?",
        "What law governs this agreement for US customers?",
        "How many days advance notice does OpenAI give for price changes on the Pricing Page?",
    ],
    "Exhibit 10.24.pdf": [
        "Who are the two parties to this agreement?",
        "What does CoreWeave warrant about the Services' performance?",
        "How many hours does Customer have to notify CoreWeave of a Security Incident?",
        "What retention policy must CoreWeave implement for Processed Customer Data?",
    ],
}

SEP = "=" * 70

for doc_name, questions in FAILING.items():
    print(f"\n{SEP}", flush=True)
    print(f"DOC: {doc_name}", flush=True)
    print(SEP, flush=True)
    pdf_path = Path('sample_docs') / doc_name
    pipeline = load_pdf(pdf_path, reuse_existing=True)

    for q in questions:
        print(f"\n{'─'*60}", flush=True)
        print(f"Q: {q}", flush=True)
        result = query(pipeline, q)

        tp = result.get('topo_pred') or {}
        topo = result.get('topology') or {}
        gate = result.get('answerability_gate') or {}

        print(f"  answerable:       {result.get('answerable')}", flush=True)
        print(f"  vote_fraction:    {result.get('vote_fraction')}", flush=True)
        print(f"  slot_score:       {result.get('slot_score'):.3f}  slot_verdict: {result.get('slot_verdict')}", flush=True)

        # CORRECT key names from actual topo_pred dict
        print(f"  topo.predicted:   {tp.get('predicted')}  score={tp.get('score'):.4f}  thr={tp.get('threshold'):.4f}  conf={tp.get('confidence')}", flush=True)

        # Gate internals
        print(f"  gate.passed:      {gate.get('passed')}  mode={gate.get('mode')}", flush=True)
        print(f"  gate.failures:    {gate.get('failures')}", flush=True)
        print(f"  gate.llm_ans:     {gate.get('llm_answerable')}  topo_pred={gate.get('topology_predicted')}  topo_score={gate.get('topology_score')}  topo_thr={gate.get('topology_threshold')}", flush=True)

        # Topo meta - what's driving the score
        meta = tp.get('meta') or {}
        print(f"  topo.meta T={meta.get('T'):.3f} A={meta.get('A'):.3f} M={meta.get('M'):.3f} O={meta.get('O'):.3f} Q={meta.get('Q'):.3f}", flush=True)
        print(f"  topo.meta llm_inline={meta.get('llm_inline_answer_present')}  base_clause_strong={meta.get('base_clause_strong_support')}  det_route={meta.get('deterministic_source_route')}", flush=True)
        print(f"  hard_gate_triggered={meta.get('hard_gate_triggered')}  hard_gate_reasons={meta.get('hard_gate_reasons')}", flush=True)

        # LLM reasoning
        print(f"  reasoning: {(result.get('reasoning') or '')[:200]}", flush=True)

        # Top retrieved nodes (with actual content)
        survivors = result.get('surviving_nodes') or []
        print(f"  surviving_nodes: {len(survivors)}", flush=True)
        for i, n in enumerate(survivors[:3]):
            t = n.get('type','?')
            src = n.get('source_text','')[:100]
            val = n.get('value') or n.get('definition') or n.get('action') or n.get('right') or n.get('trigger') or ''
            print(f"    [{i}] {t} | src: {src} | val: {str(val)[:80]}", flush=True)
