import sys, json
sys.path.insert(0, '.')
from pathlib import Path
from core_pipeline import load_pdf, query

FAILING = {
    "openai-services-agreement.pdf": [
        "Who owns the Output generated by the Services?",
        "What law governs this agreement for US customers?",
        "How many days advance notice does OpenAI give for price changes on the Pricing Page?",
    ],
    "Exhibit 10.24.pdf": [
        "Who are the two parties to this agreement?",
        "What is the Customer's full legal name?",
        "What is the Customer's address listed in the agreement?",
        "What does CoreWeave warrant about the Services' performance?",
        "How many hours does Customer have to notify CoreWeave of a Security Incident?",
        "What retention policy must CoreWeave implement for Processed Customer Data?",
    ],
}

SEP = "=" * 70

for doc_name, questions in FAILING.items():
    print(f"\n{SEP}")
    print(f"DOC: {doc_name}")
    print(SEP)
    pdf_path = Path('sample_docs') / doc_name
    pipeline = load_pdf(pdf_path, reuse_existing=True)

    for q in questions:
        print(f"\n{'─'*60}")
        print(f"Q: {q}")
        result = query(pipeline, q)

        # Gate breakdown
        gate = result.get('answerability_gate') or {}
        topo = result.get('topo_pred') or {}
        topo_raw = result.get('topology') or {}

        print(f"  answerable:    {result.get('answerable')}")
        print(f"  vote_fraction: {result.get('vote_fraction')} (llm ensemble vote)")
        print(f"  llm_answerable_raw: {result.get('llm_answerable_raw')}")
        print(f"  slot_score:    {result.get('slot_score'):.3f}")
        print(f"  slot_verdict:  {result.get('slot_verdict')}")

        print(f"  topo.pred:     {topo.get('prediction')} (conf={topo.get('confidence')})")
        print(f"  topo.score:    {topo_raw.get('score')}")
        print(f"  topo.density:  {topo_raw.get('density')}")
        print(f"  topo.coverage: {topo_raw.get('coverage')}")

        print(f"  gate passed:   {gate.get('passed')}")
        print(f"  gate reason:   {gate.get('reason')}")

        # Retrieved nodes
        survivors = result.get('surviving_nodes') or []
        print(f"  surviving_nodes: {len(survivors)}")
        for i, n in enumerate(survivors[:4]):
            ntype = n.get('type','?')
            val = n.get('value') or n.get('text','')
            chunk = n.get('_chunk_id','?')
            print(f"    [{i}] type={ntype} chunk={chunk} | {str(val)[:90]}")

        # Variants
        variants = result.get('variants') or []
        print(f"  variants ({len(variants)}):")
        for v in variants[:3]:
            print(f"    - {v[:80]}")

        # Reasoning
        reasoning = result.get('reasoning') or ''
        print(f"  reasoning: {reasoning[:200]}")
